name: Deploy the Infrastructure for an Azure Kubernetes Cluster
on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  provision-monitoring:
    uses: ./.github/workflows/provision-monitoring.yml
    secrets: inherit
    
  provision-identity:
    uses: ./.github/workflows/provision-identity.yml
    secrets: inherit
  
  provision-networking:
    uses: ./.github/workflows/provision-networking.yml
    secrets: inherit
    needs: [provision-monitoring]
    with:
      logAnalyticsWorkspaceResourceId: ${{ needs.provision-monitoring.outputs.logAnalyticsWorkspaceResourceId }}
  
  provision-app-delivery:
    uses: ./.github/workflows/provision-app-delivery.yml
    secrets: inherit
    needs: [provision-monitoring, provision-networking, provision-identity]
    with:
      logAnalyticsWorkspaceResourceId: ${{ needs.provision-monitoring.outputs.logAnalyticsWorkspaceResourceId }}
      vnetResourceId: ${{ needs.provision-networking.outputs.vnet-id }}
      subnetResourceId: ${{ needs.provision-networking.outputs.subnet-id-aag }}
      aagIdentityResourceId: ${{ needs.provision-identity.outputs.aagIdentityResourceId }}
  
  provision-container-registry:
    uses: ./.github/workflows/provision-container-registry.yml
    secrets: inherit
    needs: [provision-monitoring, provision-networking, provision-identity]
    with:
      logAnalyticsWorkspaceResourceId: ${{ needs.provision-monitoring.outputs.logAnalyticsWorkspaceResourceId }}
      vnetResourceId: ${{ needs.provision-networking.outputs.vnet-id }}
      subnetResourceId: ${{ needs.provision-networking.outputs.subnet-id-acr }}
      aksIdentityResourceId: ${{ needs.provision-identity.outputs.aksIdentityResourceId }}
  
  provision-kubernetes-cluster:
    uses: ./.github/workflows/provision-kubernetes-cluster.yml
    secrets: inherit
    needs: [provision-monitoring, provision-networking, provision-identity, provision-app-delivery, provision-container-registry]
    with:
      logAnalyticsWorkspaceResourceId: ${{ needs.provision-monitoring.outputs.logAnalyticsWorkspaceResourceId }}
      vnetResourceId: ${{ needs.provision-networking.outputs.vnet-id }}
      subnetResourceId: ${{ needs.provision-networking.outputs.subnet-id-aag }}
      aksIdentityResourceId: ${{ needs.provision-identity.outputs.aksIdentityResourceId }}
      containerRegistryResourceId: ${{ needs.provision-container-registry.outputs.acrResourceId }}
      aagResourceId: ${{ needs.provision-app-delivery.outputs.aagResourceId }}