name: Provision Monitoring

on:
    workflow_call:

jobs:
  provision-monitoring:
    environment: tno-us
    runs-on: [linux]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Repo Self-Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1        
        with:         
            tenant-id: ${{ secrets.TENANT_ID }}
            client-id: ${{ secrets.CLIENT_ID }}
            subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
            enable-AzPSSession: true

      - uses: azure/arm-deploy@v1
        name: RG Monitoring
        id: resourceGroupMonitoring
        with:
          scope: subscription
          region: ${{ vars.AZURE_REGION }}
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          deploymentName: rg-monitoring
          template: arm/templates/resource-group.json
          parameters: >
            arm/parameters/resource-group.monitoring.json
            resourceGroupLocation=${{ vars.AZURE_REGION }}
      
      - uses: azure/arm-deploy@v1
        name: Log Analytics Workspace
        id: logAnalyticsWorkspace
        with:
          template: arm/templates/log-analytics-workspace.json
          parameters: >
            arm/parameters/log-analytics-workspace.monitoring.json
          resourceGroupName: ${{ steps.resourceGroupMonitoring.outputs.resourceGroupName }}
    outputs:
      logAnalyticsWorkspaceResourceId: ${{ steps.logAnalyticsWorkspace.outputs.workspaceResourceId }}
